ArgedeSP.WebUI/Models/TravelDetayViewModel.cs
using ArgedeSP.Contracts.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArgedeSP.WebUI.Models
{
    public class TravelDetayViewModel
    {
        public Urun Urun { get; set; }
        public List<Urun> SizinIcinSectiklerimiz { get; set; }
        public List<SliderResim> SliderResim { get; set; }
        public List<UrunKategori> UrunKategorileri { get; set; }

    }
}

ArgedeSP.WebUI/Models/TravelViewModel.cs
using ArgedeSP.Contracts.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArgedeSP.WebUI.Models
{
    public class TravelViewModel
    {
      
        public List<Urun> Urunler { get; set; }
        public List<UrunKategori> UrunKategorileri { get; set; }
        public List<SliderResim> SliderResim { get; set; }

        public string altKategoriSeoUrl { get; set; }
        public string anaKategoriSeoUrl { get; set; }
        
        public string filtre { get; set; }
        public string NavbarResim { get; set; }
    }
}

ArgedeSP.WebUI/Models/TravelsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArgedeSP.WebUI.Models
{
    public class TravelsViewModel
    {
        public string anaKategoriAdi { get; set; } = "";
        public string altKategoriAdi { get; set; } = "";
        public string filtre { get; set; } = "";
    }
}

ArgedeSP.WebUI/Controllers/TravelController.cs
using ArgedeSP.Contracts.Entities;
using ArgedeSP.Contracts.Helpers;
using ArgedeSP.Contracts.Interfaces.BusinessLogicLayers;
using ArgedeSP.Contracts.Models.Common;
using ArgedeSP.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using static ArgedeSP.Contracts.Models.Common.Enums;

namespace ArgedeSP.WebUI.Controllers
{
    public class TravelController : Controller
    {
        private ISliderResimBS _sliderResimBS;
        private IUrunBS _urunBS;
        private IUrunKategoriBS _urunKategoriBS;
        private Dil SuankiDil;
        private IAnahtarDegerBS _anahtarDegerBS;

        public TravelController(IUrunBS urunBS, IUrunKategoriBS urunKategoriBS, ISliderResimBS sliderResimBS, IAnahtarDegerBS anahtarDegerBS)
        {
            _urunBS = urunBS;
            _urunKategoriBS = urunKategoriBS;
            _sliderResimBS = sliderResimBS;
            _anahtarDegerBS = anahtarDegerBS;
            SuankiDil = CultureInfo.CurrentCulture.DilGetir();

        }



        public async Task<IActionResult> TravelDetay(string urunSeoUrl)
        {



            OperationResult urun_OR = await _urunBS.UrunGetir(urunSeoUrl);
            if (!urun_OR.IsSuccess)
            {
                string hataMesaji = string.Empty;
                switch (urun_OR.Message)
                {
                    case MesajKodu.UrunBulunamadi:
                        hataMesaji = "Çözüm bulunamadı";
                        break;
                    case MesajKodu.BeklenmedikHata:
                        hataMesaji = "Beklenmedik bir hata meydana geldi";
                        break;
                }
                return RedirectToAction("Hata", "Hatalar", new { mesaj = hataMesaji });
            }

            Urun urun = (Urun)urun_OR.ReturnObject;
            if (urun.Durum == Durum.Pasif)
            {
                return RedirectToAction("Hata", "Hatalar", new { mesaj = "Ürün bulunamadı" });
            }


            OperationResult sliderResimleri_OR = await _sliderResimBS.SliderBannerResimleriGetir(SuankiDil, urun.UrunKategori.SeoUrl);

            TravelDetayViewModel travelDetayViewModel = new TravelDetayViewModel()
            {
                Urun = (Urun)urun_OR.ReturnObject,
                SizinIcinSectiklerimiz = ((List<Urun>)_urunBS.RandomKategoriGetir(4, SuankiDil, urun.UrunKategori.SeoUrl).ReturnObject).Where(x => x.Id != urun.Id).ToList(),
                SliderResim = (List<SliderResim>)sliderResimleri_OR.ReturnObject,
                UrunKategorileri = (List<UrunKategori>)(_urunKategoriBS.UrunKategorileriGetir(SuankiDil, int.MaxValue).ReturnObject)
            };

            ViewBag.Kategoriler = GetOncekiKategoriler(travelDetayViewModel);
            OperationResult description_OR = _anahtarDegerBS.AnahtarGetir(Dil.Yok, Tanimlamalar.Description);
            OperationResult titlesirketadi_OR = _anahtarDegerBS.AnahtarGetir(Dil.Turkce, Tanimlamalar.ProjeAdi);


            ViewBag.Description = ((AnahtarDeger)description_OR.ReturnObject).Deger;

            ViewBag.Title = urun.UrunAdi + " - " + ((AnahtarDeger)titlesirketadi_OR.ReturnObject).Deger;
            ViewBag.MainKeywords = urun.Keywords;
           

            return View(travelDetayViewModel);



        }

        private List<UrunKategori> GetOncekiKategoriler(TravelDetayViewModel model)
        {
            List<UrunKategori> retVal = new List<UrunKategori>();
            UrunKategori kategori = model.Urun.UrunKategori;
            while (kategori != null)
            {
                retVal.Add(kategori);
                if (kategori.UstId == null) break;
                kategori = model.UrunKategorileri.Where(x => x.Id == kategori.UstId.Value).FirstOrDefault();
            }
            retVal.Reverse();
            return retVal;
        }

        public async Task<IActionResult> Travels(string anaKategoriAdi = "", string altKategoriAdi = "", string filtre = "")
        {

            OperationResult sliderResimleri_OR = await _sliderResimBS.SliderBannerResimleriGetir(SuankiDil, altKategoriAdi);

            OperationResult urunler_OR = _urunBS.AktifUrunleriGetir(SuankiDil, anaKategoriAdi, filtre);
            List<Urun> urunler = (List<Urun>)urunler_OR.ReturnObject;

            TravelViewModel urunViewModel = new TravelViewModel();
            urunViewModel.Urunler = urunler;
            urunViewModel.UrunKategorileri = (List<UrunKategori>)(_urunKategoriBS.UrunKategorileriGetir(SuankiDil, int.MaxValue).ReturnObject);
            urunViewModel.SliderResim = (List<SliderResim>)sliderResimleri_OR.ReturnObject;
            urunViewModel.altKategoriSeoUrl = altKategoriAdi;
            urunViewModel.filtre = filtre;
            urunViewModel.anaKategoriSeoUrl = anaKategoriAdi;
            urunViewModel.Urunler.Sort((x, y) => x.UrunSira.CompareTo(y.UrunSira));
            urunViewModel.NavbarResim = urunler.FirstOrDefault()?.UrunKategori.NavbarResim;

            OperationResult description_OR = _anahtarDegerBS.AnahtarGetir(Dil.Yok, Tanimlamalar.Description);
            OperationResult titlesirketadi_OR = _anahtarDegerBS.AnahtarGetir(Dil.Yok, Tanimlamalar.TitleSirketAdi);

            switch (SuankiDil)
            {
                default:
                case Dil.Turkce:
                    ViewBag.Title = "Ürünlerimiz - " + ((AnahtarDeger)titlesirketadi_OR.ReturnObject).Deger;
                    break;

                case Dil.Ingilizce:
                    ViewBag.Title = "Products - " + ((AnahtarDeger)titlesirketadi_OR.ReturnObject).Deger;
                    break;

            }

            ViewBag.Description = ((AnahtarDeger)description_OR.ReturnObject).Deger;
            ViewBag.Kategori = urunler.FirstOrDefault()?.UrunKategori.Ad;

            return View(urunViewModel);
        }

    }
}

ArgedeSP.WebUI/Views/Travel/Travels.cshtml
@{
    ViewData["Title"] = "Gezilerimiz - EST";
}
@model TravelViewModel

<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
<link href="~/Client/assets/css/products.css" rel="stylesheet" />



<div class="banner-container">
    <img class="img-fluid" src="~/images/homePage/solutionsBg.png">
    <div class="blueOverlay"></div>

    <div class="bannerText">
        @ViewBag.Kategori
    </div>

</div>

@*<partial name="_SlickComponent" model="Model"  />*@
@(await Component.InvokeAsync("SlickComponent"))






<div class="container my-5">


    <div class="solution">
        <div class="solution-area">
            <div class="container">
                <h2>
                    İhtiyacınıza en uygun <br />yolculuğu bulalım
                </h2>
            </div>



            <div class="container">

                @{ int k = 2; }

                @foreach (var urun in Model.Urunler)
                {@if (k % 2 == 0)
                    {
                        <div class="row pt-5">

                            <div class="col-md-6" data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
                                <a asp-controller="Travel" asp-action="TravelDetay" asp-route-urunSeoUrl="@urun.SeoUrl">

                                    <img src="@Html.Raw(urun.Resim)" class="img-fluid mb-4  travel-img img-hov  zoom" />
                                </a>

                            </div>


                            <div class="col-md-6 d-flex align-items-center mb-4" data-aos="fade-left" data-aos-offset="300" data-aos-easing="ease-in-sine">
                                <div class="title-with-paragraph-solutions pl-3">
                                    <h3 class="pb-3">
                                        @Html.Raw(urun.UrunAdi)
                                    </h3>
                                    <p class="pb-3">

                                        @Html.Raw(urun.KisaAciklama)
                                    </p>
                                    @foreach (var i in urun.UrunResimGalerisi.Take(3))
                                    {
                                        <img src="@Html.Raw(i.ResimUrl)" class="img-fluid p-3  travel-small-img img-hov  zoom" />
                                    }
                                    @*<img src="~/images/homePage/aruba.png" class="img-fluid p-3" />
                                        <img src="~/images/homePage/extreme.png" class="img-fluid p-3" />*@
                                    <p>
                                        <a asp-controller="Travel" asp-action="TravelDetay" asp-route-urunSeoUrl="@urun.SeoUrl" class="read-more">
                                            <span>
                                                Seyahatı incele
                                            </span>
                                        </a>
                                    </p>
                                </div>



                            </div>
                        </div>

                        @*<div class="row pt-5">

                                <div class="col-md-6">
                                    <img src="@Html.Raw(urun.Resim)" class="img-fluid mb-4 " />
                                </div>
                                <div class="col-md-6 d-flex align-items-center mb-4">
                                    <div class="title-with-paragraph-solutions pl-3">
                                        <h3 class="pb-3">
                                            @Html.Raw(urun.UrunAdi)
                                        </h3>
                                        <p class="pb-3">
                                            @Html.Raw(urun.UzunAciklama)
                                        </p>
                                        @foreach (var i in urun.UrunResimGalerisi)
                                        {
                                            <img src="@Html.Raw(i.ResimUrl)" class="img-fluid p-3  travel-small-img img-hov  zoom" />
                                        }

                                    </div>
                                </div>
                            </div>*@
                    }
                @if (k % 2 == 1)
                {
                    <div class="row pt-5">
                        <div class="col-md-6 d-flex align-items-center mb-4" data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
                            <div class="title-with-paragraph-solutions" style=" ">
                                <h3 class="pb-3">

                                    @Html.Raw(urun.UrunAdi)
                                </h3>
                                <p class="pb-3">
                                    @Html.Raw(urun.KisaAciklama)
                                </p>
                                @foreach (var i in urun.UrunResimGalerisi.Take(3))
                                {
                                    <img src="@Html.Raw(i.ResimUrl)" class="img-fluid p-3  travel-small-img img-hov  zoom" />
                                }
                                <p>

                                    <a asp-controller="Travel" asp-action="TravelDetay" asp-route-urunSeoUrl="@urun.SeoUrl" class="read-more">
                                        <span>
                                            Seyahatı incele
                                        </span>
                                    </a>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6" data-aos="fade-left" data-aos-offset="300" data-aos-easing="ease-in-sine">
                            <a asp-controller="Travel" asp-action="TravelDetay" asp-route-urunSeoUrl="@urun.SeoUrl">

                                <img src="@Html.Raw(urun.Resim)" class="img-fluid mb-4  travel-img img-hov  zoom" />
                            </a>

                        </div>
                    </div>


                    @*<div class="row pt-5">
                            <div class="col-md-6 d-flex align-items-center mb-4">
                                <div class="title-with-paragraph-solutions" style=" ">
                                    <h3 class="pb-3">
                                        @Html.Raw(urun.UrunAdi)
                                    </h3>
                                    <p class="pb-3">
                                        @Html.Raw(urun.UzunAciklama)
                                    </p>
                                    @foreach (var i in urun.UrunResimGalerisi)
                                    {
                                        <img src="@Html.Raw(i.ResimUrl)" class="img-fluid p-3  travel-small-img img-hov  zoom" />
                                    }
                                </div>
                            </div>
                            <div class="col-md-6">
                                <img src="@Html.Raw(urun.Resim)" class="img-fluid mb-4" />
                            </div>
                        </div>*@
                }

                k++;

            }





            </div>
        </div>
    </div>

</div>



<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
<script>
    AOS.init();
</script>