ArgedeSP.WebUI/Models/HesapViewModel.cs
using ArgedeSP.Contracts.Entities;
using ArgedeSP.WebUI.Areas.Admin.Models.Hesap.Req;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArgedeSP.WebUI.Models
{
    public class HesapViewModel
    {
        public SifreGuncelle_Req SifreGuncelle_Req { get; set; }
    }
}

ArgedeSP.WebUI/Areas/Admin/Controllers/HesapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ArgedeSP.Contracts.Entities;
using ArgedeSP.Contracts.Helpers.Mail;
using ArgedeSP.Contracts.Interfaces.BusinessLogicLayers;
using ArgedeSP.Contracts.Models.Common;
using ArgedeSP.Contracts.Models.DTO.Hesap.Res;
using ArgedeSP.WebUI.Areas.Admin.Models.Hesap.Req;
using ArgedeSP.WebUI.Areas.Admin.Models.Hesap.Res;
using ArgedeSP.WebUI.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using static ArgedeSP.Contracts.Models.Common.Enums;

namespace ArgedeSP.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HesapController : Controller
    {

        private UserManager<Kullanici> _userManager;
        private SignInManager<Kullanici> _signInManager;
        private RoleManager<Rol> _roleManager;
        private readonly IEmailSender2 _emailSender;
        private readonly IRazorPartialToStringRenderer _renderer;
        private IAnahtarDegerBS _anahtarDegerBS;

        public HesapController(IPasswordHasher<Kullanici> passwordHasher,
            UserManager<Kullanici> userManager,
            SignInManager<Kullanici> signInManager,
            RoleManager<Rol> roleManager,
            IEmailSender2 emailSender,
           IRazorPartialToStringRenderer renderer,
           IAnahtarDegerBS anahtarDegerBS)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _renderer = renderer;
            _anahtarDegerBS = anahtarDegerBS;
        }



        [HttpGet]
        [AllowAnonymous]
        public IActionResult Giris(string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                    return Redirect(returnUrl ?? "/");
                if (User.IsInRole("Ogrenci"))
                {
                    if (!string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("AnaSayfa", "AnaSayfa", new { area = "Ogrenci" });
                    }
                }
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(new Giris_Req());

        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Giris(Giris_Req girisModel, string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                    return Redirect(returnUrl ?? "/");
                if (User.IsInRole("Ogrenci"))
                {
                    if (!string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("AnaSayfa", "AnaSayfa", new { area = "Ogrenci" });
                    }
                }
            }

            if (!ModelState.IsValid)
            {
                return View(girisModel);

            }

            var user = await _userManager.FindByNameAsync(girisModel.KullaniciAdi);
            if (user == null)
            {
                user = await _userManager.FindByEmailAsync(girisModel.KullaniciAdi);
                if (user == null)
                {
                    ModelState.AddModelError(nameof(girisModel.KullaniciAdi), "Bu kullanici bulunamadi");
                    return View(girisModel);
                }
            }

            if (user.Durum == Durum.Pasif)
            {
                ModelState.AddModelError(nameof(girisModel.KullaniciAdi), "Bu hesap engellenmiştir Lütfen yönetici ile iletişime geçiniz");
                return View(girisModel);
            }

            await _signInManager.SignOutAsync();
            var result = await _signInManager.PasswordSignInAsync(user, girisModel.Sifre, false, false);


            if (result.Succeeded)
            {
                IList<string> userRole = await _userManager.GetRolesAsync(user);
                if (userRole.Contains("Admin"))
                    return RedirectToAction("AnaSayfa", "AnaSayfa", new { area = "Admin" });

                if (userRole.Contains("Ogrenci"))
                    return RedirectToAction("AnaSayfa", "AnaSayfa", new { area = "Ogrenci" });

                return Redirect(returnUrl ?? "/");
            }

            ModelState.AddModelError(nameof(girisModel.Sifre), "Kullanıcı adı veya şifre hatalı");

            return View(girisModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> GirisAjax([FromBody]Giris_Req girisModel, string returnUrl)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return Json(new
                {
                    basariliMi = true,
                    donusUrl = returnUrl ?? "/"
                });
            }

            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    basariliMi = false,
                    hatalar = Helpers.Helpers.GetErrorListFromModelState(ModelState)
                });

            }

            var user = await _userManager.FindByNameAsync(girisModel.KullaniciAdi);
            if (user == null)
            {
                user = await _userManager.FindByEmailAsync(girisModel.KullaniciAdi);
                if (user == null)
                {
                    return Json(new
                    {
                        basariliMi = false,
                        hatalar = new List<string>()
                    {
                        "Kullanıcı adi bulunamadı"
                    }
                    });
                }
            }
            if (user.Durum == Durum.Pasif)
            {
                return Json(new
                {
                    basariliMi = false,
                    hatalar = new List<string>()
                    {
                        "Bu hesap engellenmiştir Lütfen yönetici ile iletişime geçiniz"
                    }
                });
            }
            await _signInManager.SignOutAsync();
            var result = await _signInManager.PasswordSignInAsync(user, girisModel.Sifre, false, false);

            if (result.Succeeded)
            {
                IList<string> userRole = await _userManager.GetRolesAsync(user);
                if (userRole.Contains("Admin"))
                {
                    return Json(new
                    {
                        basariliMi = true,
                        donusUrl = Url.Action("AnaSayfa", "AnaSayfa", new { area = "Admin" })
                    });
                }

                return Json(new
                {
                    basariliMi = true,
                    donusUrl = returnUrl
                });

            }

            ModelState.AddModelError(nameof(girisModel.Sifre), "");
            return Json(new
            {
                basariliMi = false,
                hatalar = new List<string>()
                    {
                        "Kullanıcı adı veya şifre hatalı"
                    }
            });
        }

        [HttpGet]
        public async Task<IActionResult> Cikis()
        {
            await _signInManager.SignOutAsync();
            return Redirect("/");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SifremiUnuttum(string email)
        {
            if (string.IsNullOrEmpty(email))
                return View();

            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
               
                TempData["Hata"] = "Email adresi bulunamadı.";
                return RedirectToAction("Giris");
            }

            var confrimationCode =
                    await _userManager.GeneratePasswordResetTokenAsync(user);


            AnahtarDeger projeAdi = (AnahtarDeger)_anahtarDegerBS.AnahtarGetir(Dil.Turkce, Tanimlamalar.ProjeAdi).ReturnObject;
            AnahtarDeger webSitesi = (AnahtarDeger)_anahtarDegerBS.AnahtarGetir(Dil.Yok, Tanimlamalar.SiteAdi).ReturnObject;


            SifremiUnuttum_Res sifremiUnuttum_Res = new SifremiUnuttum_Res()
            {
                KullaniciId = user.Id,
                DogrulamaKodu = confrimationCode,
                AdSoyad = user.AdSoyad(),
                ProjeAdi = projeAdi.Deger,
                WebSitesi = webSitesi.Deger
            };

            var emailHtml = await _renderer.RenderPartialToStringAsync("~/Areas/Admin/Views/Hesap/_SifremiUnuttum_EMAIL.cshtml", sifremiUnuttum_Res);
            await _emailSender.SendEmailAsync(
                email: user.Email,
                subject: "Şifre Sıfırlama",
                htmlMessage: emailHtml,
                projectName: projeAdi.Deger);

            TempData["Basarili"] = "E-mail adresine, şifre sıfırlama e-postası başarıyla gönderildi.";
            return RedirectToAction("Giris");
        }

        [AllowAnonymous]
        public IActionResult ResetSifre(string kullaniciId, string dogrulamaKodu)
        {
            if (kullaniciId == null || dogrulamaKodu == null)
                throw new ApplicationException("Parametreler yanlış");

            var model = new ResetSifre_Req { DogrulamaKodu = dogrulamaKodu };
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetSifre(ResetSifre_Req model)
        {
            if (!ModelState.IsValid)

ArgedeSP.WebUI/Areas/Admin/Views/Hesap/Giris.cshtml
@model Giris_Req
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="tr">
<!-- begin::Head -->
<head>
    <meta charset="utf-8" />
    <title>Admin Panel</title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <style>
        ::placeholder { /* Firefox, Chrome, Opera */
            color: white !important;
        }
    </style>
    <!--end::Web font -->
    <!--begin::Global Theme Styles -->
    <link href="~/Admin/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />

    <!--RTL version:<link href="~/Admin/assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <link href="~/Admin/assets/demo/demo12/base/style.bundle.css" rel="stylesheet" type="text/css" />
    <!--RTL version:<link href="~/Admin/assets/demo/default/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <!--end::Global Theme Styles -->
    <link rel="shortcut icon" type="image/svg" href="~/images/icon.png"/>

</head>

<!-- end::Head -->
<!-- begin::Body -->
<body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
    <!-- begin:: Page -->

    <div class="m-grid m-grid--hor m-grid--root m-page">
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-1" id="m_login" style="background: url(/images/homePage/maldivler.png)no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover; ">
            <div class="m-grid__item m-grid__item--fluid m-login__wrapper">
                <div class="m-login__container">
                    <div class="m-login__logo">
                        <a href="#">
                            <img src="/images/homePage/travel.jpg" style="max-height:80px" />
                        </a>
                    </div>
                    <div class="m-login__signin" style="background-color: #0000009e; padding: 15px;">
                        <div class="m-login__head">
                            <h3 class="m-login__title">Giriş</h3>
                        </div>
                        @if (TempData["Basarili"] != null)
                        {
                            <div class="alert alert-success">@TempData["Basarili"].ToString()</div>
                        }
                        @if (TempData["Hata"] != null)
                        {
                            <div class="alert alert-danger">@TempData["Hata"].ToString()</div>
                        }

                        <form class="m-login__form m-form" asp-controller="Hesap" asp-action="Giris" method="post">
                            <div class="form-group m-form__group">
                                <input asp-for="KullaniciAdi" class="form-control m-input" type="text" placeholder="Kullanıcı Adı" autocomplete="off">
                                <span class="text-white" asp-validation-for="KullaniciAdi"></span>
                            </div>
                            <div class="form-group m-form__group">
                                <input asp-for="Sifre" class="form-control m-input m-login__form-input--last" type="password" placeholder="Şifre">
                                <span class="text-white" asp-validation-for="Sifre"></span>
                            </div>
                            <div class="row m-login__form-sub">
                                <div class="col m--align-left m-login__form-left">
                                    <label class="m-checkbox m-checkbox--light">
                                        <input type="checkbox" name="remember"> Beni Hatırla
                                        <span></span>
                                    </label>
                                </div>
                                <div class="col m--align-right m-login__form-right">
                                    <a href="javascript:;" id="m_login_forget_password" class="m-link">Şifrenizi mi unuttunuz ?</a>
                                </div>
                            </div>
                            <div class="m-login__form-action">
                                <button id="m_login_signin_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-login__btn m-login__btn--primary">Giriş</button>
                            </div>
                        </form>
                    </div>
                    <div class="m-login__forget-password" style="background-color: #0000005c; padding:15px">
                        <div class="m-login__head">
                            <h3 class="m-login__title">Şifremi Unuttum</h3>
                            <div class="m-login__desc" style="color:white">Lütfen kayıtlı e-mail adresinizi giriniz</div>
                        </div>
                        <form class="m-login__form m-form" asp-controller="Hesap" asp-action="SifremiUnuttum" method="post" asp-area="Admin">
                            <div class="form-group m-form__group">
                                <input class="form-control m-input" name="email" type="text" placeholder="E-mail" autocomplete="off" style="color:white">
                            </div>
                            <div class="m-login__form-action">
                                <button id="m_login_forget_password_submit" type="submit" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary">Gönder</button>&nbsp;&nbsp;
                                <button id="m_login_forget_password_cancel" style="color:white" type="button" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn">Vazgeç</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- end:: Page -->
    <!--begin::Global Theme Bundle -->
    <script src="~/Admin/assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
    <script src="~/Admin/assets/demo/demo12/base/scripts.bundle.js" type="text/javascript"></script>
    <script src="~/Admin/assets/snippets/custom/pages/user/login.js" type="text/javascript"></script>
    <!--end::Global Theme Bundle -->
    <!--begin::Page Scripts -->
    <!--end::Page Scripts -->
</body>
<!-- end::Body -->
</html>

ArgedeSP.WebUI/Areas/Admin/Views/Hesap/ResetSifre.cshtml
@model ResetSifre_Req
@{
    ViewData["Title"] = "ResetSifre";
    Layout = null;
}


<!DOCTYPE html>
<html lang="tr">
<!-- begin::Head -->
<head>
    <meta charset="utf-8" />
    <title>Asude Kız Öğrenci Giriş Sayfası </title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <style>
        ::placeholder { /* Firefox, Chrome, Opera */
            color: white !important;
        }
    </style>
    <!--end::Web font -->
    <!--begin::Global Theme Styles -->
    <link href="~/Admin/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />

    <!--RTL version:<link href="~/Admin/assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <link href="~/Admin/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css" />

    <!--RTL version:<link href="~/Admin/assets/demo/default/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
    <!--end::Global Theme Styles -->
    <link rel="shortcut icon" href="~/favicon.svg" />
</head>

<!-- end::Head -->
<!-- begin::Body -->
<body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
    <!-- begin:: Page -->

    <div class="m-grid m-grid--hor m-grid--root m-page">
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-1" id="m_login" style="background-image: url(../../Admin/assets/app/media/img/bg/bg-giris.jpg);">
            <div class="m-grid__item m-grid__item--fluid m-login__wrapper">
                <div class="m-login__container">
                    <div class="m-login__logo">
                        <a href="#">
                            <img src="~/Client/assets/img/logo/est-logo.svg" />
                        </a>
                    </div>
                    <div class="m-login__signin" style="background-color: #0000005c; padding: 15px;">
                        <div class="m-login__head">
                            <h3 class="m-login__title">Şifre Sıfırlama</h3>
                        </div>
                        <form class="m-login__form m-form" asp-controller="Hesap" asp-action="ResetSifre" asp-area="Admin" method="post">
                            <input class="field-control" type="hidden" asp-for="DogrulamaKodu" required="required">

                            <div class="form-group m-form__group">
                                <input asp-for="Email" class="form-control m-input" type="email" placeholder="E-mail" autocomplete="user-email">
                                <span class="text-danger" asp-validation-for="Email"></span>
                            </div>
                            <div class="form-group m-form__group">
                                <input asp-for="Sifre" class="form-control m-input" type="password" placeholder="Şifre" autocomplete="off">
                                <span class="text-danger" asp-validation-for="Sifre"></span>
                            </div>
                            <div class="form-group m-form__group">
                                <input asp-for="SifreTekrar" class="form-control m-input" type="password" placeholder="Şifre Tekrarı" autocomplete="off">
                                <span class="text-danger" asp-validation-for="SifreTekrar"></span>
                                <span class="text-danger" asp-validation-for="BeklenmedikHata"></span>
                            </div>
                            <div class="m-login__form-action">
                                <button id="m_login_signin_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-login__btn m-login__btn--primary">Sıfırla</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- end:: Page -->
    <!--begin::Global Theme Bundle -->
    <script src="~/Admin/assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
    <script src="~/Admin/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>
    <script src="~/Admin/assets/snippets/custom/pages/user/login.js" type="text/javascript"></script>
    <!--end::Global Theme Bundle -->
    <!--begin::Page Scripts -->
    <!--end::Page Scripts -->
</body>
<!-- end::Body -->
</html>